name: Build

on:
    push:
        branches:
            - master

jobs:
    release:
        name: build and release electron app
        runs-on: ${{ matrix.os }}

    strategy:
        fail-fast: false
        matrix:
            os: [windows-latest, macos-latest]

    steps:
        - name: Check out git repository
          uses: actions/checkout@v3.0.0

        - name: Install Node.js
          uses: actions/setup-node@v3.0.0
          with:
              node-version: '18.16.0'

        - name: Install Dependencies
          run: yarn

        - name: Build Electron App
          run: yarn run build
          env:
              GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

        - name: upload artifacts
          uses: actions/upload-artifact@v3.0.0
          with:
              name: ${{ matrix.os }}
              path: dist/electron/Installer

        - name: release
          uses: softprops/action-gh-release@v0.1.14
          if: startsWith(github.ref, 'refs/tags/')
          with:
              files: 'dist/electron/Installer/**'
          env:
              GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
